# Generated by Django 2.0.1 on 2018-02-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('blog', '0006_auto_20180202_1354'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
